### ISSUE TITLE
Should these fetches have a client? (impacts CSP, CORS, ...)

### ISSUE THREAD

**Issue by domenic** [w3c/payment-method-manifest#1]
@annevk, I could use your help here understanding what the implications of a client for fetch are. I've gone with null for now but without much understanding of what that means.

@rsolomakhin, do we anticipate [fetching payment method manifests](https://domenic.github.io/payment-method-manifest/#fetch) to happen in a browser context, or as some kind of background operation? Basically, would it be easy to tie it back to a particular `Window` object or document? (This is a dupe of my question in the margin of https://docs.google.com/document/d/1izV4uC-tiRJG3JLooqY3YRLU22tYOsLTNq0P_InPJeE/edit# )

**Comment by domenic** [comment]
In the doc @rsolomakhin says this is done in a background process. So null client is probably the right choice. But I would still appreciate @annevk's help in understanding all the implications of this.

**Comment by annevk** [comment]
I think Fetch might have some bugs with null clients. In particular it tries to always pull an origin and fetch group out of a client, even when it's null. That can probably be fixed.

The client mostly serves as a place to pull information from, such as origin and referrer, but is also used to find the fetch group, which is the larger collection of fetches to which this one belongs and comes into play with document/Window lifetime management (which we don't quite understand still).

I did plan for it to be null sometimes though, perhaps even for this case. Is there no referrer or origin here? Does closing a tab not terminate this fetch?

**Comment by domenic** [comment]
There is indeed no referrer. I think there is no origin either? Because I think this is a "whole user-agent" background process, not one initiated by a particular web API... although, now I am confused, maybe it is initiated by part of the payment request API.

**Comment by annevk** [comment]
If there's no origin you'll also need to consider the security implications. Is this worse than a form post in some way?

**Comment by rsolomakhin** [comment]
Chrome will have a background process that scans installed payment apps and downloads their manifests. This is not triggered by any page. Currently the background process is not built, so Chrome triggers manifest download when the merchant website calls `new PaymentRequest(methods, details)`, but that's a temporary situation.

This is not worse than  a form post in any way, because it's a GET on a URL like [https://rsolomakhin.github.com/bobpay/payment-manifest.json](https://rsolomakhin.github.com/bobpay/payment-manifest.json). No data is given to the hosting website.

**Comment by annevk** [comment]
Is anything given to the merchant? Are there any other parties?

**Comment by rsolomakhin** [comment]
No information from the manifests is given to the merchant. Here're the parties:

1) The user, who has installed some payment apps with payment methods like 'https://bobpay.com'.
2) The browser, which scanned locally installed applications about 5 minutes after browser startup and found that one of them supports 'https://bobpay.com' payment method.
3) The payment method website, which hosts a manifest file on 'https://bobpay.com'.

The browser downloads the manifest files from 'https://bobpay.com' and verifies the authenticity of the locally installed payment app. When the user interacts with PaymentRequest on a merchant website that accepts payments via 'https://bobpay.com' method, the browser enables the user to use the now validated installed payment app.

**Comment by annevk** [comment]
I guess the other question I have is whether this request is made with or without credentials. Overall it seems fine though. Nothing in Fetch is extremely suitable for this scenario, but using "no-cors" and then poking through the opaque response is probably the way to go.

**Comment by rsolomakhin** [comment]
The request is made without credentials. No cookies are sent.

**Comment by domenic** [comment]
From a security perspective, it looks like this will give websites the ability to send arbitrary cross-origin GET requests to any https URL (by including that URL in the `methods` array), which is pretty bad actually... I think that will need at least security team review.

**Comment by domenic** [comment]
The alternative is to make it not part of a background process, so that we can properly associate it with a Window (and thus an origin), and then impose CORS restrictions.

**Comment by rsolomakhin** [comment]
What are the CORS restrictions?

**Comment by domenic** [comment]
https://fetch.spec.whatwg.org/#http-cors-protocol

**Comment by annevk** [comment]
CORS only protects the data coming back. You can already make any kind of outgoing GET request if you want. However, if the API can indeed trigger requests, that should probably be governed by CSP, in which case you need a client... It's a little weird though if they're sometimes fetched by the API and sometimes by random encounter.

**Comment by rsolomakhin** [comment]
I previously wrote:

> Chrome will have a background process that scans installed payment apps and downloads their manifests. This is not triggered by any page. Currently the background process is not built, so Chrome triggers manifest download when the merchant website calls `new PaymentRequest(methods, details)`, but that's a temporary situation.

In our implementation experience, we found that triggering the manifest download when the merchant website calls `new PaymentRequest(methods,details)` has acceptable performance, so we've decided to keep this solution. Therefore, nothing is blocking us from adding a client to the requests. I'm OK with this.

**Comment by annevk** [comment]
The other thing that's relevant here is whether these can go through a service worker or not. It sounds like these might be subresource requests in which case they'd go through the client's service worker, but maybe that's wrong?

**Comment by rsolomakhin** [comment]
@annevk Not sure what you mean by request going through the service worker. Can you elaborate, please? (Just so that we're on the same page here.)

**Comment by domenic** [comment]
Service workers allow JS code running on the client to intercept and modify requests/responses. ([More info](https://developers.google.com/web/fundamentals/primers/service-workers/).) Most (all?) subresources requested by the page are interceptable by a service worker, so this is probably the right choice for payment method manifests, but we want to be sure.

I'll work on a spec PR that starts to work on this.
