### ISSUE TITLE
Front matter needs adjusting for W3C FPWD

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/payment-method-manifest#15]
In order to get to FPWD, the front matter needs to conform to pubrules. I can help if the spec is in respec, but unfortunately cannot if it's in bikeshed.

Ian

**Comment by domenic** [comment]
Hopefully you can ask another W3C staff to help you with this part of the process; I know a number of them are versed in Bikeshed.

**Comment by ianbjacobs** [comment]
@sideshowbarker are you one of those people?

Ian
cc @plehegar

**Comment by sideshowbarker** [comment]
I’m not an experienced hand at Bikeshed but we might be able to get @TabAtkins himself to make a little time to give some guidance on the frontmatter setup

**Comment by tabatkins** [comment]
Easy enough to fix - take one of the folders in `bikeshed/boilerplate` that looks like what you want, copy it and give it a name for your group (whatever that is), then make whatever wording edits are necessary to specialize it to your group. Gimme a PR and I'll happily merge it.

**Comment by rsolomakhin** [comment]
@domenic Does your commit make this a FPWD now?

**Comment by domenic** [comment]
No, still leaving that to staff.

**Comment by domenic** [comment]
Seems to be done.
