### ISSUE TITLE
Updating references to other payments specs

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/payment-method-manifest#16]
Due to repo changes, it will be necessary to update URLs to PR API, PMI, and Payment Handler API. Also, Payment Handler has moved to FPWD and the list of editors
needs to be updated.

Ian

**Comment by domenic** [comment]
Hi Ian, have you checked the latest spec? I believe all these were fixed by https://github.com/w3c/payment-method-manifest/commit/266759058bb5b8a938490861ca7c463e3dc72526

**Comment by ianbjacobs** [comment]
Cool, thanks! 

(I had not checked the spec between reading replies from my previous PR and recasting a couple of them as issues.)

Ian
