### ISSUE TITLE
Suggest rephrasing language for web developers

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/payment-method-manifest#17]
Hi all,

In one section there are normative statements for user agent implementers followed by non-normative statements for web developers, followed by normative statements for user agent implementers.

I propose removing these statements:

  " Web developers must ensure that all of their [=payment method manifests=] are [=valid=]. 
   <p class="note">As with all conformance requirements, these are web-developer facing, and not-implementer-facing.</p>"

And adding after the section ending "including invalid ones." add:

     <p class="note">Web developers are responsible for ensuring that all of their [=payment method manifests=] are [=valid=].</p>

Ian

**Comment by domenic** [comment]
> In one section there are normative statements for user agent implementers followed by non-normative statements for web developers, followed by normative statements for user agent implementers.

Are you referring to https://w3c.github.io/payment-method-manifest/#format ?

That section only contains normative statements for web developers, not any statements (normative or non-normative) for user agent implementers.

**Comment by ianbjacobs** [comment]
Hi @domenic,

I see what you mean. I misread them the first time. 

However, I think this phrase is throwing me: "As with all conformance requirements, these are web-developer facing, and not implementer-facing."

Other specifications do include browser-facing conformance requirements, so it is not clear to me why this one would not also include some. 

It does seem that in section two, all the conformance requirements are aimed at web developers.
so perhaps the sentence could simply say: "The requirements in this section are web-developer facing, and not implementer-facing."
