### ISSUE TITLE
Relative URL for "default_applications"

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/payment-method-manifest#25]
The spec requires absolute URLs for `"default_applications"`, which creates difficulty in working with test servers, which we use for integration tests in Chrome. Would it be acceptable to allow relative URLs in `"default_applications"` as well?

cc: @domenic

**Comment by domenic** [comment]
Relative to what though? The page calling `new PaymentRequest()`, or the payment method manifest?

I guess probably we should allow this, since IIRC web app manifests do that too. Relative to the payment method manifest, in that case. We can change this, unless @marcoscaceres has any concerns.

**Comment by rsolomakhin** [comment]
Relative to the location of the payment method manifest.

**Comment by marcoscaceres** [comment]
No concerns from me.
