### ISSUE TITLE
URL resolution may be wrong

### ISSUE THREAD

**Issue by domenic** [w3c/payment-method-manifest#38]
From what I can tell, the URL resolution inside a PMM is done relative to the PMI URL, not to the actual PMM URL (which might be different due to the Link redirect).

I'm hopeful that in our implementation, we resolve relative to the PMM URL. @rsolomakhin can you confirm? In that case this is likely just a spec bug which I can quickly fix.

Concrete example: a PMI of `https://alicepay.com/` which Links to a PMM at `https://alicepay.com/pay/payment-manifest.json` which has `"default_applications": ["app/webappmanifest.json"]`. I believe per the current spec that should to fetch `https://alicepay.com/app/webappmanifest.json`, but to me the obvious correct answer is instead `https://alicepay.com/pay/app/webappmanifest.json`.

**Comment by rsolomakhin** [comment]
Implementation today rejects relative URLs inside of the `payment-manifest.json`, but that's a bug in the implementation. Please make the spec do the right thing and the implementation will follow.
