### ISSUE TITLE
Spec cleanup for "default_applications"

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/payment-method-manifest#44]
Currently the spec describes "default_applications" contents as absolute URLs in some places and as relative URL in others, including the parsing algorithm. The spec should be cleaned up to use relative URLs everywhere, because that is most convenient for web developers.

**Comment by domenic** [comment]
Hmm, from what I can see the spec is pretty clear about them always being parsed relative to the appropriate base URL. Is there a specific part that seems broken to you?

**Comment by rsolomakhin** [comment]
https://w3c.github.io/payment-method-manifest/#use-cases says:

> This is accomplished via the requirement that every payment method whose identifier is URL-based will provide a payment method manifest file in JSON format containing two key pieces of information:
> * any default payment apps that are associated with this payment method, referenced as **absolute-URL** strings giving the URL of their web app manifests; and

**Comment by domenic** [comment]
Ah, darn, the non-normative section got out of sync with the normative one! This should indeed instead link to [valid URL string](https://url.spec.whatwg.org/#valid-url-string), like https://w3c.github.io/payment-method-manifest/#format does.
