### ISSUE TITLE
Migrate to a W3C org?

### ISSUE THREAD

**Issue by RByers** [w3c/payment-method-manifest#5]
@rsolomakhin [mentions](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/gQCGIrnMxFU/Fz0UDLNeBAAJ) that there's interest from Mozilla, right?  Then can we perhaps migrate this repo to WICG or some other place with IPR protection?  We know that some vendors (eg. Microsoft) can be hesitant to provide feedback until a spec is in a place with some minimal IPR protection.

**Comment by zkoch** [comment]
I think we're going to move this into the Web Payments WG

**Comment by RByers** [comment]
Ok, that works too.  If there's any difficulty getting it there quickly we can always go to WICG first.  Though if it's only Mozilla whose likely to review and provide feedback before we ship then it hopefully doesn't really make a difference where it lives.

**Comment by zkoch** [comment]
I think it should be no problem, the group already formally voted to take this up as a work item. My plan is to propose we move it to FPWD. I'll be sharing it on the WG call this Thursday

**Comment by ianbjacobs** [comment]
MIgrated today: https://github.com/w3c/payment-method-manifest/

**Comment by domenic** [comment]
@ianbjacobs can you add me as a collaborator, preferably with "admin" permissions? It should be under Settings > Collaborators & teams.

**Comment by ianbjacobs** [comment]
You are already listed as a collaborator. I have moved your perms to Admin.
